spring:

  datasource:
    url: jdbc:mysql://root:1234@localhost:3306/moonuDb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sq: true

logging:
  pattern:
    dateformat: "HH:mm:ss.SSS"
  file:
    name: log/logFile.log

