spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data/fileDb
    driverClassName: org.h2.Driver
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  pattern:
    dateformat: "HH:mm:ss.SSS"
  file:
    name: log/logFile.log

